fix: Ensure Content-Type is included in request headers
applandinc/appmap-ruby pull request #218
Opened 2022-02-10 19:55 UTC by kgilpin

Rack doesn’t prepend HTTP_ to the content type header, so we are usually/always missing it on requests.

2022-02-10 20:22 UTC, apotterri requested changes
🤯

2022-02-10 20:22 UTC, apotterri commented on lib/appmap/util.rb
> +        # Rack prepends HTTP_ to all client-sent headers (except Content-Type and Content-Length?).
It seemed so bizarre to me that these two headers would be treated differently, I went off and researched why.

Turns out rack is just following the CGI spec: https://datatracker.ietf.org/doc/html/rfc3875#section-4.1.18 .

Will you add a comment to that effect, please, and include that link to the RFC?

2022-02-10 20:27 UTC, kgilpin commented
Ok. Maybe we should be sure and get Authorization also.

On Thu, Feb 10, 2022 at 3:22 PM Alan Potter ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> 🤯
> ------------------------------
>
> In lib/appmap/util.rb
> <https://github.com/applandinc/appmap-ruby/pull/218#discussion_r804073767>
> :
>
> > @@ -121,15 +121,16 @@ def select_rack_headers(env)
>
>            blank?(headers) ? nil : headers
>
>          end
>
>
>
> -        # Rack prepends HTTP_ to all client-sent headers.
>
> +        # Rack prepends HTTP_ to all client-sent headers (except Content-Type and Content-Length?).
>
>
> It seemed so bizarre to me that these two headers would be treated
> differently, I went off and researched why.
>
> Turns out rack is just following the CGI spec:
> https://datatracker.ietf.org/doc/html/rfc3875#section-4.1.18 .
>
> Will you add a comment to that effect, please, and include that link to
> the RFC?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/appmap-ruby/pull/218#pullrequestreview-879395265>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC62UQZDVKG5DD3XK3YLU2QNATANCNFSM5OB3KAHA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-11 12:00 UTC, merged

2022-02-11 12:15 UTC, appland-release commented
:tada: This PR is included in version 0.72.2 :tada:

The release is available on:
- `v0.72.2`
- [GitHub release](https://github.com/applandinc/appmap-ruby/releases/tag/v0.72.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: