Allow skipping railtie if APPMAP_INITIALIZE=false
applandinc/appmap-ruby pull request #84
Opened 2020-10-01 15:14 UTC by dividedmind

Also, don't track `.ruby-version`; it's a gem and should be developed and tested with different Ruby versions.

2020-10-01 15:54 UTC, kgilpin requested changes
In order to release this, it would be best to update the version and changelog

2020-10-02 12:14 UTC, dividedmind commented
> In order to release this, it would be best to update the version and changelog

I updated the changelog but I didn't think the change is worth a release and a version bump all in itself, especially since nothing depends on it. I figured it'd be included in a future bump.

2020-10-02 12:16 UTC, kgilpin commented
Ok, as long as you aren’t relying on anyone picking up / not picking up
this change.

On Fri, Oct 2, 2020 at 8:14 AM Rafał Rzepecki <notifications@github.com>
wrote:

> In order to release this, it would be best to update the version and
> changelog
>
> I updated the changelog but I didn't think the change is worth a release
> and a version bump all in itself, especially since nothing depends on it. I
> figured it'd be included in a future bump.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/appmap-ruby/pull/84#issuecomment-702700494>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC6YZOGRJVBOZZOGW6XTSIW72BANCNFSM4SASAL4Q>
> .
>

2020-10-02 12:16 UTC, kgilpin approved these changes

2020-10-02 20:47 UTC, merged