Supported versions section added to About
applandinc/appmap-ruby pull request #99
Opened 2021-01-21 18:51 UTC by ptrdvrk

Supported versions section added to the About chapter in README.md

2021-01-21 19:18 UTC, apotterri requested changes

2021-01-21 19:18 UTC, apotterri commented on README.md
> +* Rails 4, 5, 6
Kevin's got a PR open that removes Rails 4, because it's been EOLed. This should just be `Rails 5, 6` now.

2021-01-21 20:39 UTC, kgilpin commented on README.md
> +* Ruby 2.5, 2.6
2.7 is about to be supported

2021-01-22 00:15 UTC, ptrdvrk commented on README.md
> +* Ruby 2.5, 2.6
2.7 added in the latest commit.

2021-01-22 11:35 UTC, apotterri approved these changes

2021-01-22 11:36 UTC, merged